env:
language: node_js
node_js:
  - "node"
before_script:
  - cd frontend
  - yarn install
script:
  - yarn lint
  - yarn test:unit
cache:
  directories:
    - "node_modules"
    - "frontend/node_modules"
